# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Pricing-table"
  description:
  icon: "view_week"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  subtitle: 
  card_title:
  price: 
  frequency: 
  list_1: 
  list_2: 
  list_3: 
  list_4: 
  list_5: 
  list_6: 
  button: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "PRICING TABLE"
  subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
  card_title: "STARTER PACK"
  price: "$40"
  frequency: " /month"
  list_1: "Unlimited Downloads"
  list_2: "Unlimited Uploads"
  list_3: "Unlimited Email Accounts"
  list_4: "Email Forwards"
  list_5: "Cloud Storage"
  list_6: "Screen Share"
  button: "Buy Now"


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
