# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description: "Hero banner with title, text, background image and buttons"
  icon: "title"
  tags: [hero]

# Defines the structure of this component, as well as the default values
blueprint:
  title:
  title_color: "#80d6a3"
  text: 
  text_color: "white"
  image: 
  image_alt: 
  button_1: bookshop:generic/button
  button_2: bookshop:generic/button
  reversed: false
  background_color: "#6d6969"
  scrolldown_to: "/"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "Clean and Flexible Business Template"
  title_color: "white"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."
  text_color: "white"
  image: '/img/hero-banner.jpg'
  image_alt: "Person working"
  button_1: bookshop:generic/button
  button_2: bookshop:generic/button
  reversed: false
  background_color: "#6d6969"
  scrolldown_to: "/"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
