# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description: "Hero banner with title, text, background image and buttons"
  icon: "title"
  tags: [hero]

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  text: 
  image: 
  image_alt: 
  button_1:
    label: 
    variant: 
  button_2:
    label: 
    variant: 
  reversed: false


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "Clean and Flexible Business Template"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."
  image: '/img/hero-banner.jpg'
  image_alt: "Person working"
  button_1:
    label: "Purchase Now"
    variant: "transparent"
  button_2:
    label: "View Features"
    variant: "transparent"
  reversed: false

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
