# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Narrow-image"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: "/img/desk.jpj"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
 image: "/img/desk.jpj"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
