# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Form"
  description:
  icon: "alternate_email"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: 
    title: 
    subtitle: 
    title_color: 
    subtitle_color: 
    line_color: 
  button: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: 
    title: "CONTACT US"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
    title_color: "primary-2"
    subtitle_color: "primary-3"
    line_color: "primary-1"
  button: "SEND"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
