# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Pricing-table"
  description:
  icon: "view_week"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Hello"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: 
    title: "PRICING TABLE"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously Dantes remained confused and silent by this explanation of the thoughts which had unconsciously "
    title_color: "primary-2"
    subtitle_color: "primary-3"
    line_color: "white"
  price_card:
    - title: "STARTER PACK"
      currency_unit: "$"
      price: 40
      frequency: " /month"
      list_1: "Unlimited Downloads"
      list_2: "Unlimited Uploads"
      list_3: "Unlimited Email Accounts"
      list_4: "Email Forwards"
      list_5: "Cloud Storage"
      list_6: "Screen Share"
      button: bookshop:generic/button
    - title: "MEDIUM PACK"
      currency_unit: "$"
      price: 60
      frequency: " /month"
      list_1: "Unlimited Downloads"
      list_2: "Unlimited Uploads"
      list_3: "Unlimited Email Accounts"
      list_4: "Email Forwards"
      list_5: "Cloud Storage"
      list_6: "Screen Share"
      button: bookshop:generic/button
    - title: "EXPERIENCED PACK"
      currency_unit: "$"
      price: 80
      frequency: " /month"
      list_1: "Unlimited Downloads"
      list_2: "Unlimited Uploads"
      list_3: "Unlimited Email Accounts"
      list_4: "Email Forwards"
      list_5: "Cloud Storage"
      list_6: "Screen Share"
      button: bookshop:generic/button

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
