# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Features"
  description:
  icon: "view_compact"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  subheading: 
  heading_1: 
  text_1: 
  heading_2: 
  text_2: 
  heading_3: 
  text_3: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "OUR BEST SERVICES"
  subheading: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
  heading_1: "Responsive Design"
  text_1: "Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"
  heading_2: "Outstanding Animation"
  text_2: "Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"
  heading_3: "Unlimited Colors"
  text_3: "Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
