# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Features"
  description:
  icon: "view_compact"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: 
    title: 
    subtitle: 
    title_color: 
    subtitle_color: 
    line_color: 
  features:
    - icon_path:
      heading: 
      text: 
      features_heading_color: "white"
      features_text_color: "white"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_color: "#fff"
  heading: 
    _bookshop_name: generic/heading
    title: "OUR BEST SERVICES"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
    title_color: "#333"
    subtitle_color: "#333"
    line_color: "#80d6a3"
  features:
    - icon_path:
      heading: "Responsive Design"
      text: "Now with range. Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"
    - icon_path:
      heading: "Outstanding Animation"
      text: "Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"
    - icon_path:
      heading: "Unlimited Colors"
      text: "Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"
  features_heading_color: "white"
  features_text_color: "white"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
