# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Testimonial"
  description:
  icon: "grid_view"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "TESTIMONIAL"
  subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
  image: "/img/service-img.png"
  image_alt: "person"
  heading: "Jonathon Andrew"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
