# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Blog-card"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  title_color: "#333"
  line_color: "#333"
  image: 
  image_alt: 
  author: 
  date: 
  author_details_color: "#6d6969"
  description: 
  description_color: "#333"
  url:
   

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "Blog Card for Blogs"
  title_color: "#333"
  line_color: "#333"
  image: "/img/blog/blog1.jpg"
  image_alt: "green bird feathers"
  author: "Bob Smart"
  date: "18th September, 2022"
  author_details_color: "#6d6969"
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus ex itaque repudiandae nihil qui debitis atque necessitatibus aliquam, consequuntur autem!"
  description_color: "#333"
  url: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
