# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Logo"
  description: Client logo
  icon: person_outline
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: 
  image_alt: 
  link:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: "/img/clientLogo/Generic_Logo.png"
  image_alt: "Client logo"
  link: "/"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
