# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: 

  label_color: 
  variant: 
  hover_background: 
  hover_label: 
  hover_border: 
  open_in_new_tab: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "Get Started Free"
  link_url: '/components'
  label_color: "white"
  background_color: "primary-1"
  hover_background: "white"
  hover_label: "primary-2"
  hover_border: "primary-2"
  open_in_new_tab: false

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label_color:
    type: select
    options:
      values:
        - "primary-1"
        - "priamry-2"
        - "primary-3"
        - "white"
        - "black"
  variant:
    type: select
    options:
      values:
        - "transparent"
        - "primary-1"
        - "priamry-2"
        - "primary-3"
        - "white"
        - "black"
  hover_background:
      type: select
      options:
        values:
        - "primary-1"
        - "priamry-2"
        - "primary-3"
        - "white"
        - "black"
  hover_label:
      type: select
      options:
        values:
        - "primary-1"
        - "priamry-2"
        - "primary-3"
        - "white"
        - "black"
  hover_border:
      type: select
      options:
        values:
        - "primary-1"
        - "priamry-2"
        - "primary-3"
        - "white"
        - "black"